### ISSUE TITLE
Remove episodes 7+

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-intro-geospatial#1]
For the adaptation of these lessons for the Geospatial curriculum, we will be removing most or all of the material in episodes 7 and above. Please look through the content of episodes 7+ to confirm that we can safely remove them from this repo.

**Comment by lachlandeer** [comment]
Have done a first pass at this, though left some material on `dplyr`, `ggplot` and saving data & plots since I think we use this in the geospatial data.
