### ISSUE TITLE
Synthesize "Exploring Data frames"

### ISSUE THREAD

**Issue by lachlandeer** [datacarpentry/r-intro-geospatial#10]
**Problem**: We want to shrink down the entire lesson, and this section is quite long.

**Task**: reduce the quantity of information in this lesson / alter the structure.

* A first pass at this might be to try integrate the components of the work with the feline data into the 'realistic example' using gapminder. And then restructure so that the most important parts appear closer to the front.

**Comment by annefou** [comment]
So my plan is to change:
04-data-structures-part1 --> remove feline dataset example and instead start to create a small "gapminder-like" dataset to show how to write csv files in R, then move to gapminder-FiveYearData.csv
05-data-structures-part2 --> Remove feline example and keep gapminder part only and integrate the components of the work with the feline data into the 'realistic example' using gapminder

**Comment by lachlandeer** [comment]
This sounds good.

Don't focus too much on the "gapminder like" part of a data set. We have been talking about moving away from it... What would be great is to use the real data as much as possible and less of the feline example

**Comment by ErinBecker** [comment]
Ok to close?

**Comment by ErinBecker** [comment]
Closing with #16.
