### ISSUE TITLE
Episode 3 Data Structures: Adjust Challenge 3 for factors/strings

### ISSUE THREAD

**Issue by cengel** [datacarpentry/r-intro-geospatial#104]
Challenge 3 still assumes that the default setting for `read.csv` is `stringsAsFactors = TRUE`. 

https://github.com/datacarpentry/r-intro-geospatial/blob/3ae8234810c878a3b99dc3fc4b6c2ba68d2f4c58/_episodes_rmd/03-data-structures-part1.Rmd#L354

**Comment by angela-li** [comment]
Bumping this as we came across it in a recent workshop. I may have students do the opposite - reading in data and setting stringsAsFactors = TRUE even though the new default is FALSE

**Comment by angela-li** [comment]
Looks like #110 updates this and could be incorporated!

**Comment by jsta** [comment]
Have you reviewed #110 and it looks good to you @angela-li? If so, I'll go ahead and merge with your second opinion in-hand.

It looks good to me, but I haven't verified that it's all accurate.

**Comment by angela-li** [comment]
Yes, you can merge it! There are many places in this curriculum that need to be updated to reflect default factors as well, I can look through the open issues/PRs

**Comment by angela-li** [comment]
Since this was merged in https://github.com/datacarpentry/r-intro-geospatial/commit/a55e98e3ba691cb84f8e48e06c53980d2e28f1df, I think we can close this issue as well @jsta?
