### ISSUE TITLE
Episode 2 Project Management With RStudio: A Possible Solution - here::here() instead of getwd()

### ISSUE THREAD

**Issue by lquayle88** [datacarpentry/r-intro-geospatial#123]
Suggest using the here package for finding the top level directory of a project and building system-agnostic file paths relative to this.

Install the here package:

`install.packages("here")`

Load the here package:

`library("here")`

The here package creates paths relative to the top-level directory and the package displays the top-level of the current project on load or any time you call the `here()` function:

`here()`
`#> [1] "/home/user/dir/subdir/project_top_level"`

You can build a path relative to the top-level directory:

`here("data", "example_data.csv")`
`#> [1] "/home/user/dir/subdir/project_top_level/data/example_data.csv"`

These relative paths can be used in order to read or write a file:

`readr::read_csv(here("data", "example_data.csv"))`

**Comment by mikemahoney218** [comment]
Howdy @lquayle88 ! I'm [one of the maintainers](https://datacarpentry.org/lessons/#geospatial-curriculum) for this lesson :smile: 

Would you be able to show me where in the lesson you'd like to change to use `here`? I see `getwd()` in the [episode 2 intro](https://datacarpentry.org/r-intro-geospatial/02-project-intro/), but not anywhere else in the project. I agree that using `here` is a good practice, but would be a bit worried about losing focus if we went into the details of the `here` package, especially if the rest of the lesson is using relative paths and not moving the working directory around.

**Comment by lquayle88** [comment]
Hi @mikemahoney218. Thanks for the speedy reply!

Yes, getwd() is used in the introduction of the project so I was suggesting replacing that with a brief introduction to `here` for two reasons:

1) getwd() works in the manner suggested when the working directory has defaulted to the project top level upon opening a project but will not work if this changes for some reason (nor will any relative path used later in the lesson) but `here()` will always find the path to the top level of an open project

2) later in the lesson relative paths are built (to read the data for example) and using `here` will not only ensure these paths are robust in the event that the working directory becomes altered (this can happen), but also means that the paths can be built in a system agnostic manner; some users may be using windows machines on which backslashes are used rather than forward slashes and the relative paths in the later episodes all show forward slashes.

I understand the balancing act when it comes to focus but given that using `here` appears to be creeping in as the "best practice" when it comes to writing portable R code and how quickly it could be covered to a sufficient level, it is my opinion that an episode called "Project Management in RStudio" would be the ideal place to lay this foundation for novice users.

All of this is just a suggestion of course &#x1F60A;

**Comment by mikemahoney218** [comment]
re: 2, I _believe_ (though haven't confirmed) that you can use forward slashes on Windows, it's just not how system commands return file paths :smile: 

As for the main conversation, I'm going to tag in @datacarpentry/curriculum-advisors-geospatial for some additional opinions! It's worth noting that we use relative paths throughout the workshop (for instance, https://preview.carpentries.org/r-raster-vector-geospatial/01-raster-structure.html ) and not just in this lesson, so if we made this change I think it'd ideally be applied across lessons.

**Comment by mikemahoney218** [comment]
Sorry for the delay on this issue! After talking with the rest of the CAC, we decided:

1. We currently don't want to switch the workshop (both this lesson as well as the other lessons) over to using `here`; while we use and love the package, we worry that introducing the package at the start of the project management lesson will confuse learners. We'd rather keep focusing on using R projects and relative paths for filesystem management.
2. That said, we think it's worth adding an instructor note both to mention "if you _want_ to introduce `here`, this is a good place to do it" and to have instructors ensure all learners are using a new project.

**Comment by lquayle88** [comment]
@mikemahoney218 Thanks for the reply. I had forgotten about this to be honest 😅 I think based on what you said that's a good compromise. I hope it was a useful conversation. I love `here` and find that my students find it easy to understand for managing paths within a project so just thought it was a suggestion worth raising 😊
