### ISSUE TITLE
ggplot2 package

### ISSUE THREAD

**Issue by LizZhou** [datacarpentry/r-intro-geospatial#142]
In the introduction part of ggplot2 (https://github.com/datacarpentry/r-intro-geospatial/blob/main/episodes/07-plot-ggplot2.Rmd), it was saying the ggplot2 was the most effective for creating publication quality graphics. I agree with that, however, I'm wondering if it's better to say it's one of the best because determining the best also depends on the needs of the users I think.

**Comment by mikemahoney218** [comment]
Even though I do think ggplot2 is the best (😆), I agree with this change! We might also consider "one of the leading" or "one of the most popular" (but I'm comfortable with your version as well).

@LizZhou , do you want to contribute a PR to do this?
