### ISSUE TITLE
Change in  the sequence of the episode Introduction to R and RStudio

### ISSUE THREAD

**Issue by ShailyGandhi** [datacarpentry/r-intro-geospatial#20]
In the Introduction to R and RStudio episode 

I would recommend explaining the hidden variable before giving it in Challenge 1

Challenge 2 and 3 Should be placed in Variables and assignment section 

Challenge 4 should be in the section where remove object is discussed 

R Packages section should include some example and also some basic errors and ways to handle them should be included in this section. 
"unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'" 

Challenge 5 needs to be a below section of R Packages and can include removing and updating package codes instead of just installing the given packages.

**Comment by ErinBecker** [comment]
Thanks @ShailyGandhi - this is great feedback. I agree that the exercises/challenges need to be distributed through the epsiode so that Instructors know when to use them and so they directly follow the relevant parts of the lesson. I will put in a PR now to address this.

**Comment by ErinBecker** [comment]
This should close automatically when https://github.com/datacarpentry/r-intro-geospatial/pull/40 is merged.
