### ISSUE TITLE
Project Management Directory Tips under "Data Cleaning" are not consistent or complementary. 

### ISSUE THREAD

**Issue by mapninja** [datacarpentry/r-intro-geospatial#21]
The two tips on directory structure are not complementary and cause a little confusion. First you explain one set of "Good Enough Practice" directories to use for data management, then have people use the ProjectTemplate package to create a DIFFERENT set of directories, but don't explain their use. 

Might to be a good idea to combine them by simply adopting the ProjectTemplate package method and explaining how to use the directory structure it provides, rather than illuminating the use of one set of directories in the first, then demonstrating a package that installs a different set of directories and NOT explaining their relevance.

**Comment by ErinBecker** [comment]
Good catch @mapninja. This was fixed with https://github.com/datacarpentry/r-intro-geospatial/pull/25.
