### ISSUE TITLE
suggestions for trimming down this lesson

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-intro-geospatial#22]
I know that there's been a lot of discussion about how to make this lesson shorter to ensure that there is enough time during the workshop to really dig deeply into working with raster and vector data in R. 

Here are my suggestions for things to remove from this lesson (organized by episode). I'm making these suggestions from the perspective of comparing this R lesson with the Data Carpentry Ecology R lesson - there are some things that aren't covered in the Ecology lesson, and the learners do fine without it. If, however, these topics are needed specifically for working with raster or vector data, then we shouldn't take them out!

**In total, my suggested cuts would save 235 minutes, cutting this lesson down from almost 8 hours to 4 hours.** 

[Introduction to R and RStudio](http://www.datacarpentry.org/r-intro-geospatial/01-rstudio-intro/)
- [x] Mathematical functions
- [x] Vectorization (I know this is going to cause controversy, but introducing this so early is counter productive. Better to introduce this in a practical context later on.)
- [x] Managing your environment
- [x] R Packages - **add this intro to first time an external package is used**
These suggestions would bring the episode down to ~20 minutes teaching and 5 minutes exercises (save 30 minutes). **Addressed with https://github.com/datacarpentry/r-intro-geospatial/pull/24**

[Project Management with RStudio](http://www.datacarpentry.org/r-intro-geospatial/02-project-intro/)
- [x] ProjectTemplate - a possible solution
- [x] Separate function definition and application
- [x] avoiding duplication
- [x] Tip: command line in R Studio
- [x] Version Control
All of these are good strategies, but too advanced and/or theoretical for the audience that typically attends DC workshops. 
These suggestions would bring the episode down to 10 minutes teaching and 5 minutes exercises (saves 15 minutes). **Addressed with https://github.com/datacarpentry/r-intro-geospatial/pull/25.**

[Seeking Help](http://www.datacarpentry.org/r-intro-geospatial/03-seeking-help/)
I tend to skip this episode and mention the things that it talks about at various points in the rest of the R lesson I'm teaching. I find that at this point in the lesson learners haven't seen more than one or two functions (and none if we get rid of the mathematical functions section above), so the concept of reading help files for functions just isn't applicable to them yet. 
If we do keep this episode, I suggest getting rid of:
- [x] Special operators
- [x] When you have no idea where to begin
- [x] When your code doesn’t work: seeking help from your peers (too advanced)
and keeping just the first two challenges.
20 minutes saved by getting rid of these episode entirely. 10 minutes saved if the above sections removed. **Addressed with https://github.com/datacarpentry/r-intro-geospatial/pull/26.**

[Data Structures](http://www.datacarpentry.org/r-intro-geospatial/04-data-structures-part1/)
~~I suggest removing this episode entirely and moving into the [Exploring Data Frames](http://www.datacarpentry.org/r-intro-geospatial/05-data-structures-part2/) episode. All of the data structures (other than lists) are covered in that episode. If this episode is kept, the following sections can be removed.~~
- [ ] ~~Data Types~~
- [ ] ~~Factors (these are covered in depth in the next episode)~~
- [ ] ~~Lists (unless needed for the raster vector lessons)~~
~~Save 55 minutes if this episode is removed entirely. These suggestions would bring the episode down to 25 minutes teaching and 10 minutes exercises (saves 20 minutes).~~ (see comment in thread below)

[Exploring Data Frames](http://www.datacarpentry.org/r-intro-geospatial/05-data-structures-part2/)
- [x] shorten output cells in this episode, the full dataframe is printed each time and it's hard to read the lesson
**Addressed with https://github.com/datacarpentry/r-intro-geospatial/pull/27.**

[Subsetting Data](http://www.datacarpentry.org/r-intro-geospatial/06-data-subsetting/)
- [ ] ~~I suggest changing the examples in this episode so that they all refer to the Gapminder data that the learners just read into their environment in the previous episode. Moving back to a toy / unrealistic data example is counter productive here.~~ (see comment in thread below)
- [x] Tip: Non-unique names
- [x] List subsetting (unless needed for working with the data in the raster vector lesson.
These suggestions shorten the episode to 25 minutes teaching, 10 minutes exercises (saves 15 minutes).
**Addressed with https://github.com/datacarpentry/r-intro-geospatial/pull/29**

[Control Flow](http://www.datacarpentry.org/r-intro-geospatial/07-control-flow/)
- [x] I recommend getting rid of this episode entirely, unless if statements and loops are required for the raster vector lesson.
(saves 60 minutes).
**Addressed with https://github.com/datacarpentry/r-intro-geospatial/pull/30**

[Creating Publication-quality Graphics](http://www.datacarpentry.org/r-intro-geospatial/08-plot-ggplot2/)
- [x] This episode has already been shortened from [the original](http://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/) and is now probably about 50 minutes teaching (not 60). I recommend also removing: 
- [x] Transformations and statistics
- [x] Modifying text
These can be covered in more depth in the raster vector lessons where they will be more relevant to the learners.
These suggestions shorten the episode to 25 minutes teaching, 10 minutes exercises (saves 45 minutes).
**Addressed with https://github.com/datacarpentry/r-intro-geospatial/pull/34**

[Writing Data](http://www.datacarpentry.org/r-intro-geospatial/09-writing-data/)
- no changes suggested

[Dataframe manipulation with dplyr](http://www.datacarpentry.org/r-intro-geospatial/09-dplyr/)
- [x] Connect mutate with logical filtering: ifelse
- [x] Combining dplyr and ggplot2
- [x] Advanced Challenge
These suggestions shorten the episode to 30 minutes teaching and 10 minutes exercises (saves 15 minutes)
**Addressed with https://github.com/datacarpentry/r-intro-geospatial/pull/34**

[Writing good software](http://www.datacarpentry.org/r-intro-geospatial/10-wrap-up/)
Recommend deleting this episode as it focuses on practices for writing software, not for data analysis. Many of the same principles apply, but the focus doesn't seem to me right for a data analytic focused audience.
This suggestion would save 15 minutes.
**Addressed with https://github.com/datacarpentry/r-intro-geospatial/pull/34**

**Comment by chris-prener** [comment]
all of these changes look reasonable to me @ErinBecker

**Comment by ErinBecker** [comment]
Thanks @chris-prener. I'll go ahead and get started on this today, but will check back here frequently to see if anyone has any objections to these cuts. I'll be putting in short PRs in case there are differences of opinions about keeping / getting rid of some of this material. Would appreciate reviews from you or anyone else!

**Comment by juanfung** [comment]
@ErinBecker I like the proposed cuts, and am in favor of cutting the "Seeking Help" and "Data Structures" episodes entirely

**Comment by lachlandeer** [comment]
I agree with you; maybe one thing i would keep though maybe in a different (yet unknown form) is "data structures" - knowing these is key for understanding output and some unexpected function behaviour when debugging.... 

but maybe we should rebalance it with closer related content to the geospatial lesson once its been completed a little more

**Comment by ErinBecker** [comment]
Thanks @juanfung and @lachlandeer for the feedback. I'll take a closer look at the data structures section when I get there and put in some proposals. Please be on the lookout for PRs today and Monday!

**Comment by ErinBecker** [comment]
Per my suggestion earlier: 
- [ ] I suggest changing the examples in this episode (subsetting data) so that they all refer to the Gapminder data that the learners just read into their environment in the previous episode. Moving back to a toy / unrealistic data example is counter productive here.

I realize now why it's necessary to use the toy dataset. In order to use the Gapminder data to explain how to subset vectors, you would first need to subset the dataframe to extract a column or row. This would mean explaining dataframe subsetting first, which is more difficult, so this lesson uses a toy dataset to explain vector subsetting rather than explaining dataframe subsetting first. It is possible to do this the other direction (dataframe --> vector), and I believe that is what is done in the Ecology R lessons, but it would take a lot of reconfiguration. These lessons work in the order they are written, so let's not mess with it for now.

**Comment by ErinBecker** [comment]
In looking through the full lesson again, I'm hesitant to remove the data structures episodes (as I proposed above). While it's possible to teach R from a data frames perspective and introduce different data structures from within a data frame (as done in the R Ecology lesson), this would take a fair bit of restructuring. I don't think it is necessary to do this at this point, but may be worth investigating in the future, depending on how learners react to this lesson organization.

**Comment by gklarenberg** [comment]
Hi - I'm a newly minted instructor and got myself into trying to contribute to the Geospatial lessons.
My 2 cents: I think the Writing Data section needs to be changed. It uses `write.table` - saying that `read.table` was also used before, but I think that is incorrect. The gapminder data is read in with `read.csv`. So I suggest changing this section to using `write.csv`. That cuts out all the trouble with the quotation marks.
I would also suggest to use the figure that is generated at the end of the previous lesson to show how to save. And leave out the `facet_grid()` addition. That way this part can literally be done in 5 minutes.

**Comment by jsta** [comment]
@gklarenberg I second using `write.csv` over `write.table`. Less sure about dropping `facet_grid` because I wonder if would decrease the _wow factor_ for learners.

**Comment by gklarenberg** [comment]
@jsta Re `facet_grid()` - possibly. I just couldn't get it to produce anything logical with the data and set-up used in the previous exercise (aimed to continue and build on that). I'll admit that for me it's also a personal issue; I can never get `facet_grid()` to do what I want it to do, so I hardly ever use it.

**Comment by ErinBecker** [comment]
I think we can remove the `facet_grid()` here since the learners will be doing faceting in later lessons (in the raster vector lesson).

**Comment by ErinBecker** [comment]
I am also in favor of changing to `write.csv()`. Would you like to put in a PR for that change @gklarenberg or would you prefer someone else to do it? I'm working on these lessons about 20 hours this week, so happy to do it if you don't have time. :-)

**Comment by lachlandeer** [comment]
Agreed on the `write.csv()`
