### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-intro-geospatial#3]
The README.md file gives a lot of information about the original repo that this lesson was copied from. Update the Maintainer names, Slack badges, and any other information that is changing.

**Comment by lachlandeer** [comment]
Hi @ErinBecker 

What do we do with the `AUTHORS` file? Do we leave it as is for now?

**Comment by ErinBecker** [comment]
Good question @lachlandeer. From my understanding, the `AUTHORS` file is auto-generated when the lessons are prepared for publication. We can leave it as is for now, or delete it. 

@fmichonneau to double check that this is correct.

**Comment by fmichonneau** [comment]
yes, the AUTHORS is generated automatically during releases
