### ISSUE TITLE
Links in instructor notes don't work

### ISSUE THREAD

**Issue by angela-li** [datacarpentry/r-intro-geospatial#57]
Not exactly sure how the lesson is being built, but the links to other lessons in the instructor notes for [Introduction to R for Geospatial Data](https://datacarpentry.org/r-intro-geospatial/guide/index.html) don't work. Looks like the base URL isn't being picked up for some reason?

**Comment by jsta** [comment]
I'm stumped. The links work in the `r-raster-vector-geospatial` instructor notes. They are the same format as this repo and `_includes/base_path.html` looks identical. Maybe this lesson just needs to be rebuilt?
