### ISSUE TITLE
contribution submitted by email

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-intro-geospatial#60]
The following is an instructor-training email contribution to the Data Carpentry lesson "Introduction to R for Geospatial Data", as a part of my instructor training checkout. Attached is a pdf and R Markdown file with the proposed change. I hope this contribution is helpful. Please let me know if I can provide additional materials. 

My contribution could fit in the 03-data-structures part of the lesson here (https://datacarpentry.org/r-intro-geospatial/03-data-structures-part1/index.html ) just under "Data Types".

As data structures are being introduced, why introduce two numeric variables, xLongitude and yLatitude, and plot them with both 'plot' from the base graphics library and with 'map' from the 'maps' package? 
----------------------------
Requirements: R version 3.5.0 or higher, internet connection to install one R library 
Optional: R Studio 1.1.453 or higher
Purpose: gain early success with geospatial data in R with less than ten lines of code 
Reason for change or update: The lesson could use a simple, early-success geospatial data example, prior to more in-depth procedures. 
Lesson learned: R has built-in plotting capabilities, which can be used for visualizing geospatial data. With the addition of the "maps" package, this plotting can be used with base map elements such as the United States and World base maps. 
----------------------------

Code: 

xLongitude <- 106.67
yLatitude <- 35.07
class(xLongitude)

plot(xLongitude,yLatitude) 

install.packages("maps")
library(maps)

map("usa")
points(x,y, col="gray")

[geospatial_edit.txt](https://github.com/datacarpentry/r-intro-geospatial/files/3175152/geospatial_edit.txt)

**Comment by jsta** [comment]
I agree it's good for learners to know about built-in data. However, I'm not sure this is the best place in the workshop to introduce it. The `maps` package data isn't really one of `numeric`, `character`, etc. 

I could see adding something like this in [r-raster-vector-geospatial/Create Publication-quality Graphics](https://datacarpentry.org/r-raster-vector-geospatial/13-plot-time-series-rasters-in-r/index.html) to show adding a (probably ggplot) basemap to an existing point layer.

**Comment by lachlandeer** [comment]
I agree with @jsta - this lesson is not the place for it, and adding it might cause more confusion by adding a new 'non-standard' data type.

**Comment by ErinBecker** [comment]
Thanks for the quick feedback @jsta  and @lachlandeer. I'll go ahead and close this issue.
