### ISSUE TITLE
clarifying download step (submitted by email for instructor training checkout)

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-intro-geospatial#66]
on the Setup page, clarify that the Nordic datasets used in the Project Management and Data Structures lessons will be downloaded in Challenge 1 of the Project Management lesson. At the top of the Data Structures lesson, it currently states, "Let's start by downloading and reading in a file nordic-data.csv." I recommend adding a note that points users to either the Challenge 1 in the Project Management lesson, or to an addendum to the Setup section. Similarly, pointing users to the "Exploring Data Frames" lesson to allow them to catch up and download the gapminder dataset if they are in the "Subsetting Data" lesson would be great. Alternatively, this download could also be added to the "Setup" page.

**Comment by lachlandeer** [comment]
Hi - This looks like its been merged in - so I am going to close this issue. 

Feel free to reopen it if you think it needs further attention

Thanks!
