### ISSUE TITLE
Update Maintainers/Authors in README.md

### ISSUE THREAD

**Issue by LucaDiStasio** [datacarpentry/r-intro-geospatial#77]
Hi,

It appears that the list of maintainers is not up-to-date. It does not match the list provided at https://datacarpentry.org/lessons/ (geospatial curriculum section). It would be good to update it. Is everything correct with the list provided at the previous link? Can I update based on that?
Previous maintainers could be listed under a "Previous maintainers" or "Alumni maintainers" section, to acknowledge their contribution. Do you agree?
Finally, a list of authors (original developers of the lesson) should be included as well in a separate section. Who are the original authors?

Luca

**Comment by lachlandeer** [comment]
Yep

Definitely needs updating - not sure if these has been done since before the initial release.

Perhaps setting it up to look like this:

https://github.com/datacarpentry/R-ecology-lesson?

thoughts welcomed

L

**Comment by LucaDiStasio** [comment]
Nice example, I think we could follow it.
I can make the changes and then we can review it.

Let me know.
Luca

**Comment by lachlandeer** [comment]
Sure thing

@jsta - might be useful to move all the geospatial workshop readmes to this newer format? How about once we get the one here set up we copy the style across to all?

**Comment by jsta** [comment]
@lachlandeer Sounds good to me!
