### ISSUE TITLE
solutions not expanding

### ISSUE THREAD

**Issue by sheilasaia** [datacarpentry/r-intro-geospatial#83]
I’m working through the Intro to R for Geospatial Data lesson for my training demo and noticing that solutions in each of the episodes of this lesson are not expanding. Is this something others are experiencing? For example, see https://datacarpentry.org/r-intro-geospatial/03-data-structures-part1/index.html. I tired expanding them on both Chrome and Firefox so it doesn’t seem to be a browser thing.

**Comment by fmichonneau** [comment]
fixed by #84
