### ISSUE TITLE
Remove all ggplot facet wrap examples

### ISSUE THREAD

**Issue by lachlandeer** [datacarpentry/r-intro-geospatial#9]
To synthesize this episode it would be good to remove all instances of `facet_wrap()` since it is not essential to know to move into the Geospatial with R lesson.

This means we should do the following in episode 8:

* Change the "modifying text" section to have an example that doesn't facet_wrap
* Remove challenge 5
* Create a different challenge that allows learners to create a different plot and do some text modifications with axis labels

**Comment by lachlandeer** [comment]
There is also a stack of facet_wrapping in the `dplyr` lesson, would be good to think of a simpler version of the current content without it

**Comment by lachlandeer** [comment]
Let's actually put a hold on this, it looks like some of the later r-raster-vector lesson might need faceting to efficiently produce multi-row/column plots 

I think it's best to wait and see how datacarpentry.org/r-raster-vector/#133 develops

**Comment by ErinBecker** [comment]
The only place where `facet`ing appears in the current version of the lessons is in a challenge in [episode 7 "Writing Data"](https://datacarpentry.org/r-intro-geospatial/07-writing-data/index.html)
![screen shot 2018-07-10 at 2 17 09 pm](https://user-images.githubusercontent.com/19176319/42538167-01505472-844c-11e8-890b-34647bf5b944.png)

It is not (yet) used in any of the raster vector episodes: 
![screen shot 2018-07-10 at 2 17 09 pm](https://user-images.githubusercontent.com/19176319/42538260-4735ec86-844c-11e8-99a9-d1a726b5d3c5.png)

I recommend that we remove the exercise in episode 7 and leave faceting for the raster vector lessons if they decide to add it to those lessons.

**Comment by ErinBecker** [comment]
See also the comments in favor of removing `facet_grid` at the end of https://github.com/datacarpentry/r-intro-geospatial/issues/22.

**Comment by ErinBecker** [comment]
If we can get a final ruling on this from one or more of the Maintainers (@lachlandeer @juanfung @janu123), I'm happy to put in a PR to remove the last vestige of `facet` in this lesson.

**Comment by juanfung** [comment]
I agree, let's remove from this lesson.
