### ISSUE TITLE
PR run failed: Build and Deploy Website

### ISSUE THREAD

**Issue by annajiat** [datacarpentry/r-intro-geospatial#97]
@lachlandeer @juanfung @LucaDiStasio @zkamvar @fmichonneau 

There are 10 open Pull requests (PR), https://github.com/datacarpentry/r-intro-geospatial/pulls

All of them seems to have red cross, probably suggesting, PR run failed: Build and Deploy Website

Would it be possible to check?

Is it an upstream issue or is it something specific to our repository?

Is there any guidance or actionable items for the contributors?

How can I help?

**Comment by juanfung** [comment]
@annajiat Thank you for pointing this out. I've run into a similar issue for [https://github.com/datacarpentry/r-socialsci/issues/294](r-socialsci) this week. I think it's an issue with github actions, but not sure how to fix it. If you have any ideas, that would be great!

**Comment by zkamvar** [comment]
Hi @annajiat and @juanfung, the fix for this is to merge a PR from the styles repo and remove the Build and Deploy Website workflow (example: https://github.com/swcarpentry/r-novice-inflammation/pull/505). I can initiate it if you would like.

There is a caveat that the 'master' branch will need to switch to 'main' (which I can do for you). Luckily, GitHub will give you instructions for updating the repo on your local computer.

**Comment by annajiat** [comment]
@juanfung ,
could you please approve @fmichonneau 's PR at https://github.com/datacarpentry/r-intro-geospatial/pull/98
That might solve the errors.
If that does not solve the problems, then we can then request @zkamvar for help or get back to @fmichonneau

**Comment by juanfung** [comment]
@annajiat Sorry for the delay, it's done! Hopefully that solves the problem.

**Comment by zkamvar** [comment]
Thank you for merging this. As I noted in #98, I changed the default branch to "main", so you will need to update the branch information on your local computer:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by juanfung** [comment]
Awesome thank you @zkamvar !

**Comment by zkamvar** [comment]
Just checking in: can this issue be closed?
